# To use this file, drag it out of `src/`.
# It should be in the same directory as `Cargo.toml`.

# Your bot's discord token
token = YOUR_TOKEN_HERE_IN_QUOTES

# Your YouTube Data API key
key = YOUR_KEY_HERE_IN_QUOTES

# List of user IDs of bot administrators
admins = [  ]

